[package]
name = "guts"
version = "0.1.0"
edition = "2023_11"
authors = ["Abdel <@AbdelStark>"]
license = "MIT"
keywords = ["starknet", "git", "signature"]
categories = ["onchain", "cryptography"]

[dependencies]
starknet = "2.6.0"
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria", branch = "main" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.12.0" }

[tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[tool.snforge]
exit_first = true
